/// Daily menu. Written by the Head Cook / Kitchen admin. Published weekly.
class DayMenu {
  final DateTime date;
  final Meal breakfast;
  final Meal lunch;
  final Meal supper;

  const DayMenu({
    required this.date,
    required this.breakfast,
    required this.lunch,
    required this.supper,
  });

  factory DayMenu.fromMap(Map<String, dynamic> m) => DayMenu(
    date: DateTime.parse(m['menu_date'].toString()),
    breakfast: Meal(
      (m['breakfast'] as String?) ?? '',
      (m['breakfast_side'] as String?) ?? '',
    ),
    lunch: Meal(
      (m['lunch'] as String?) ?? '',
      (m['lunch_side'] as String?) ?? '',
    ),
    supper: Meal(
      (m['supper'] as String?) ?? '',
      (m['supper_side'] as String?) ?? '',
    ),
  );
}

class Meal {
  final String main;
  final String side;
  const Meal(this.main, this.side);
}

enum EventCategory {
  academic,
  coCurricular,
  community;

  static EventCategory fromKey(String? k) => EventCategory.values.firstWhere(
    (e) => e.name == k,
    orElse: () => EventCategory.academic,
  );
}

/// School event. Written by Director / Registrar. Reminders (push + SMS)
/// fire 48 h before.
class SchoolEvent {
  final String id;
  final String title;
  final DateTime startsAt;
  final DateTime? endsAt;
  final String? venue;
  final String? audience; // Boarding parents
  final EventCategory category;
  final bool highlight; // Visitation Day etc.

  const SchoolEvent({
    required this.id,
    required this.title,
    required this.startsAt,
    required this.category,
    this.endsAt,
    this.venue,
    this.audience,
    this.highlight = false,
  });

  factory SchoolEvent.fromMap(Map<String, dynamic> m) => SchoolEvent(
    id: m['id'] as String,
    title: (m['title'] as String?) ?? '',
    startsAt: DateTime.parse(m['starts_at'].toString()),
    endsAt: m['ends_at'] == null
        ? null
        : DateTime.tryParse(m['ends_at'].toString()),
    venue: m['venue'] as String?,
    audience: m['audience'] as String?,
    category: EventCategory.fromKey(m['category'] as String?),
    highlight: (m['highlight'] as bool?) ?? false,
  );
}

/// Document published to parents (fee structure, calendar, handbook) or
/// tied to one student (signed consent form). Written by Registrar/Bursar.
class SchoolDocument {
  final String id;
  final String title;
  final String? subtitle; // PDF · 340 KB  or  Signed 03 Feb 2024
  final String url;
  final String? studentId; // null = school-wide

  const SchoolDocument({
    required this.id,
    required this.title,
    required this.url,
    this.subtitle,
    this.studentId,
  });

  factory SchoolDocument.fromMap(Map<String, dynamic> m) => SchoolDocument(
    id: m['id'] as String,
    title: (m['title'] as String?) ?? '',
    subtitle: m['subtitle'] as String?,
    url: (m['url'] as String?) ?? '',
    studentId: m['student_id'] as String?,
  );
}

enum NoticeKind {
  payment,
  clinic,
  academics,
  event,
  general;

  static NoticeKind fromKey(String? k) => NoticeKind.values.firstWhere(
    (e) => e.name == k,
    orElse: () => NoticeKind.general,
  );
}

/// An item in the parent's "Recent" feed / notification inbox. Generated by
/// the system whenever another role writes something about the student.
class Notice {
  final String id;
  final NoticeKind kind;
  final String title;
  final String subtitle;
  final DateTime at;
  final int? amount; // for payment notices
  final bool read;
  final String? studentId;

  const Notice({
    required this.id,
    required this.kind,
    required this.title,
    required this.subtitle,
    required this.at,
    this.amount,
    this.read = false,
    this.studentId,
  });

  factory Notice.fromMap(Map<String, dynamic> m) => Notice(
    id: m['id'] as String,
    kind: NoticeKind.fromKey(m['kind'] as String?),
    title: (m['title'] as String?) ?? '',
    subtitle: (m['subtitle'] as String?) ?? '',
    at: DateTime.parse(m['created_at'].toString()),
    amount: (m['amount'] as num?)?.toInt(),
    read: (m['read'] as bool?) ?? false,
    studentId: m['student_id'] as String?,
  );
}
