import 'package:flutter/material.dart';
import 'package:provider/provider.dart';
import 'package:url_launcher/url_launcher.dart';

import '../../../core/format.dart';
import '../../../models/academics.dart';
import '../../../theme/tokens.dart';
import '../../../widgets/brand.dart';
import '../parent_provider.dart';
import '../parent_shell.dart';
import 'child_switcher.dart';

class AcademicsScreen extends StatelessWidget {
  const AcademicsScreen({super.key});

  @override
  Widget build(BuildContext context) {
    final p = context.watch<ParentProvider>();
    final rc = p.report;
    final child = p.child;

    return Column(
      children: [
        ParentPageHeader(title: 'Academics', badge: p.term?.label),
        Expanded(
          child: ListView(
            padding: const EdgeInsets.fromLTRB(20, 0, 20, 24),
            children: [
              const ChildSwitcher(),
              const SizedBox(height: 12),
              if (child == null)
                const SizedBox.shrink()
              else if (rc == null)
                _NotReleased(termLabel: p.term?.label ?? '')
              else ...[
                _ReportCard(rc: rc, studentShort: child.shortName, house: child.house),
                const SizedBox(height: 12),
                Row(
                  children: [
                    Expanded(
                      child: FilledButton.icon(
                        onPressed: rc.pdfUrl == null
                            ? null
                            : () => launchUrl(Uri.parse(rc.pdfUrl!), mode: LaunchMode.externalApplication),
                        icon: const Icon(Icons.picture_as_pdf_outlined, size: 18),
                        label: const Text('Download PDF'),
                      ),
                    ),
                    const SizedBox(width: 10),
                    Expanded(
                      child: OutlinedButton.icon(
                        onPressed: () => _share(context, rc, child.fullName),
                        icon: const Icon(Icons.ios_share_rounded, size: 18),
                        label: const Text('Share'),
                      ),
                    ),
                  ],
                ),
                if (rc.pdfUrl == null)
                  const Padding(
                    padding: EdgeInsets.only(top: 8),
                    child: Text(
                      'The signed PDF is generated by the school once the headteacher stamps the report.',
                      textAlign: TextAlign.center,
                      style: TextStyle(fontSize: 11, color: TgsColors.fg3),
                    ),
                  ),
              ],
            ],
          ),
        ),
      ],
    );
  }

  void _share(BuildContext context, ReportCard rc, String name) {
    // Native share sheet requires share_plus; use a summary snackbar until
    // the Android Intent is wired in the staff/production build.
    final avg = rc.results.isEmpty
        ? 0
        : (rc.results.fold<int>(0, (a, r) => a + r.total) / rc.results.length).round();
    ScaffoldMessenger.of(context).showSnackBar(
      SnackBar(content: Text('$name · ${rc.termLabel} · ${rc.positionLabel} · avg $avg/100')),
    );
  }
}

class _NotReleased extends StatelessWidget {
  const _NotReleased({required this.termLabel});
  final String termLabel;
  @override
  Widget build(BuildContext context) => TgsCard(
    padding: const EdgeInsets.all(24),
    child: Column(
      children: [
        const IconBox(Icons.hourglass_top_rounded, tint: TgsColors.navy500, size: 48),
        const SizedBox(height: 12),
        Text(
          'Report card not yet released',
          style: Theme.of(context).textTheme.titleMedium,
        ),
        const SizedBox(height: 6),
        Text(
          'Teachers are still entering $termLabel marks. You will receive a notification the moment the Director of Studies publishes it.',
          textAlign: TextAlign.center,
          style: const TextStyle(fontSize: 13, color: TgsColors.fg2),
        ),
      ],
    ),
  );
}

class _ReportCard extends StatelessWidget {
  const _ReportCard({required this.rc, required this.studentShort, required this.house});
  final ReportCard rc;
  final String studentShort, house;

  @override
  Widget build(BuildContext context) {
    return Container(
      clipBehavior: Clip.antiAlias,
      decoration: BoxDecoration(
        color: Colors.white,
        borderRadius: BorderRadius.circular(TgsRadius.xl),
        border: Border.all(color: TgsColors.border1),
        boxShadow: TgsShadows.sh2,
      ),
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          const FlagStrip(height: 4),
          Padding(
            padding: const EdgeInsets.fromLTRB(16, 14, 16, 16),
            child: Column(
              crossAxisAlignment: CrossAxisAlignment.start,
              children: [
                Row(
                  crossAxisAlignment: CrossAxisAlignment.start,
                  children: [
                    Expanded(
                      child: Column(
                        crossAxisAlignment: CrossAxisAlignment.start,
                        children: [
                          Eyebrow('Timbitwire Girls · ${rc.termLabel}'),
                          const SizedBox(height: 4),
                          Text.rich(
                            TextSpan(
                              text: 'Report card ',
                              style: const TextStyle(fontFamily: TgsFonts.display, fontSize: 22),
                              children: [
                                TextSpan(
                                  text: '· $studentShort',
                                  style: const TextStyle(color: TgsColors.fg3),
                                ),
                              ],
                            ),
                          ),
                          const SizedBox(height: 2),
                          Text(
                            '${rc.className} · $house House · ${rc.positionLabel}',
                            style: const TextStyle(fontSize: 12, color: TgsColors.fg2),
                          ),
                        ],
                      ),
                    ),
                    const _Stamp(),
                  ],
                ),
                const SizedBox(height: 14),
                _Grid(rc.results),
                if (rc.classTeacherComment != null) ...[
                  const SizedBox(height: 14),
                  const Eyebrow("Class teacher's comment"),
                  const SizedBox(height: 6),
                  Text(
                    rc.classTeacherComment!,
                    style: const TextStyle(fontSize: 13, height: 1.5, color: TgsColors.fg1),
                  ),
                  const SizedBox(height: 6),
                  Text(
                    '— ${rc.classTeacherName ?? 'Class teacher'}${rc.publishedAt == null ? '' : ' · ${Fmt.dayMonthYear(rc.publishedAt!)}'}',
                    style: const TextStyle(
                      fontFamily: TgsFonts.display,
                      fontStyle: FontStyle.italic,
                      fontSize: 12,
                      color: TgsColors.maroon600,
                    ),
                  ),
                ],
              ],
            ),
          ),
        ],
      ),
    );
  }
}

class _Stamp extends StatelessWidget {
  const _Stamp();
  @override
  Widget build(BuildContext context) => Transform.rotate(
    angle: -.12,
    child: Container(
      width: 62,
      height: 62,
      alignment: Alignment.center,
      decoration: BoxDecoration(
        shape: BoxShape.circle,
        border: Border.all(color: TgsColors.maroon500.withValues(alpha: .55), width: 2),
      ),
      child: Text(
        'HEAD-\nTEACHER\nSTAMP',
        textAlign: TextAlign.center,
        style: TextStyle(
          fontSize: 7,
          fontWeight: FontWeight.w800,
          letterSpacing: .8,
          height: 1.3,
          color: TgsColors.maroon500.withValues(alpha: .7),
        ),
      ),
    ),
  );
}

class _Grid extends StatelessWidget {
  const _Grid(this.rows);
  final List<SubjectResult> rows;

  static const _h = TextStyle(
    fontSize: 10,
    fontWeight: FontWeight.w700,
    letterSpacing: .8,
    color: TgsColors.fg3,
  );

  @override
  Widget build(BuildContext context) {
    return Table(
      columnWidths: const {
        0: FlexColumnWidth(2.2),
        1: FlexColumnWidth(1),
        2: FlexColumnWidth(1),
        3: FlexColumnWidth(.9),
      },
      border: const TableBorder(
        horizontalInside: BorderSide(color: TgsColors.border1),
        bottom: BorderSide(color: TgsColors.border1),
        top: BorderSide(color: TgsColors.border1),
      ),
      children: [
        TableRow(
          decoration: const BoxDecoration(color: TgsColors.paper),
          children: [
            _cell(const Text('SUBJECT', style: _h)),
            _cell(const Text('CAT', style: _h), right: true),
            _cell(const Text('EXAM', style: _h), right: true),
            _cell(const Text('GRADE', style: _h), center: true),
          ],
        ),
        for (final r in rows)
          TableRow(
            children: [
              _cell(Text(r.subject, style: const TextStyle(fontSize: 13, fontWeight: FontWeight.w600))),
              _cell(Text('${r.catScore}/${r.catOutOf}', style: _mono), right: true),
              _cell(Text('${r.examScore}/${r.examOutOf}', style: _mono), right: true),
              _cell(_GradeChip(r.grade), center: true),
            ],
          ),
      ],
    );
  }

  static const _mono = TextStyle(
    fontFamily: TgsFonts.mono,
    fontSize: 12,
    fontWeight: FontWeight.w500,
    color: TgsColors.fg2,
  );

  Widget _cell(Widget child, {bool right = false, bool center = false}) => Padding(
    padding: const EdgeInsets.symmetric(vertical: 8, horizontal: 4),
    child: Align(
      alignment: center
          ? Alignment.center
          : right
          ? Alignment.centerRight
          : Alignment.centerLeft,
      child: child,
    ),
  );
}

class _GradeChip extends StatelessWidget {
  const _GradeChip(this.g);
  final String g;
  @override
  Widget build(BuildContext context) {
    final good = g.startsWith('D');
    final ok = g.startsWith('C');
    final (bg, fg) = good
        ? (TgsColors.maroon500, Colors.white)
        : ok
        ? (TgsColors.navy50, TgsColors.navy600)
        : (TgsColors.dangerBg, TgsColors.brick600);
    return Container(
      padding: const EdgeInsets.symmetric(horizontal: 8, vertical: 3),
      decoration: BoxDecoration(color: bg, borderRadius: BorderRadius.circular(6)),
      child: Text(
        g,
        style: TextStyle(fontFamily: TgsFonts.mono, fontSize: 12, fontWeight: FontWeight.w600, color: fg),
      ),
    );
  }
}
